/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppFraudRouteImport } from './routes/app.fraud'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCampaignsIndexRouteImport } from './routes/app.campaigns.index'
import { Route as AppInfluencerIdRouteImport } from './routes/app.influencer.$id'
import { Route as AppCampaignsNewRouteImport } from './routes/app.campaigns.new'
import { Route as AppCampaignsIdRouteImport } from './routes/app.campaigns.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminInfluencersRouteImport } from './routes/app.admin.influencers'
import { Route as AppAdminFraudReportsRouteImport } from './routes/app.admin.fraud-reports'
import { Route as AppAdminCampaignsRouteImport } from './routes/app.admin.campaigns'
import { Route as AppAdminAnalyticsRouteImport } from './routes/app.admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppFraudRoute = AppFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppInfluencerIdRoute = AppInfluencerIdRouteImport.update({
  id: '/influencer/$id',
  path: '/influencer/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInfluencersRoute = AppAdminInfluencersRouteImport.update({
  id: '/admin/influencers',
  path: '/admin/influencers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFraudReportsRoute = AppAdminFraudReportsRouteImport.update({
  id: '/admin/fraud-reports',
  path: '/admin/fraud-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCampaignsRoute = AppAdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/discover': typeof AppDiscoverRoute
  '/app/fraud': typeof AppFraudRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/fraud-reports': typeof AppAdminFraudReportsRoute
  '/app/admin/influencers': typeof AppAdminInfluencersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/influencer/$id': typeof AppInfluencerIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/fraud': typeof AppFraudRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/fraud-reports': typeof AppAdminFraudReportsRoute
  '/app/admin/influencers': typeof AppAdminInfluencersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/influencer/$id': typeof AppInfluencerIdRoute
  '/app/campaigns': typeof AppCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/campaigns': typeof AppCampaignsRouteWithChildren
  '/app/discover': typeof AppDiscoverRoute
  '/app/fraud': typeof AppFraudRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/campaigns': typeof AppAdminCampaignsRoute
  '/app/admin/fraud-reports': typeof AppAdminFraudReportsRoute
  '/app/admin/influencers': typeof AppAdminInfluencersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/influencer/$id': typeof AppInfluencerIdRoute
  '/app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/discover'
    | '/app/fraud'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/admin/analytics'
    | '/app/admin/campaigns'
    | '/app/admin/fraud-reports'
    | '/app/admin/influencers'
    | '/app/admin/users'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/influencer/$id'
    | '/app/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/analytics'
    | '/app/discover'
    | '/app/fraud'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/admin/analytics'
    | '/app/admin/campaigns'
    | '/app/admin/fraud-reports'
    | '/app/admin/influencers'
    | '/app/admin/users'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/influencer/$id'
    | '/app/campaigns'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/analytics'
    | '/app/campaigns'
    | '/app/discover'
    | '/app/fraud'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/admin/analytics'
    | '/app/admin/campaigns'
    | '/app/admin/fraud-reports'
    | '/app/admin/influencers'
    | '/app/admin/users'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/influencer/$id'
    | '/app/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fraud': {
      id: '/app/fraud'
      path: '/fraud'
      fullPath: '/app/fraud'
      preLoaderRoute: typeof AppFraudRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/': {
      id: '/app/campaigns/'
      path: '/'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/app/influencer/$id': {
      id: '/app/influencer/$id'
      path: '/influencer/$id'
      fullPath: '/app/influencer/$id'
      preLoaderRoute: typeof AppInfluencerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns/new': {
      id: '/app/campaigns/new'
      path: '/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/app/campaigns/$id': {
      id: '/app/campaigns/$id'
      path: '/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/influencers': {
      id: '/app/admin/influencers'
      path: '/admin/influencers'
      fullPath: '/app/admin/influencers'
      preLoaderRoute: typeof AppAdminInfluencersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/fraud-reports': {
      id: '/app/admin/fraud-reports'
      path: '/admin/fraud-reports'
      fullPath: '/app/admin/fraud-reports'
      preLoaderRoute: typeof AppAdminFraudReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/campaigns': {
      id: '/app/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/app/admin/campaigns'
      preLoaderRoute: typeof AppAdminCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/analytics': {
      id: '/app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/app/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFraudRoute: typeof AppFraudRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminCampaignsRoute: typeof AppAdminCampaignsRoute
  AppAdminFraudReportsRoute: typeof AppAdminFraudReportsRoute
  AppAdminInfluencersRoute: typeof AppAdminInfluencersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppInfluencerIdRoute: typeof AppInfluencerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFraudRoute: AppFraudRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminCampaignsRoute: AppAdminCampaignsRoute,
  AppAdminFraudReportsRoute: AppAdminFraudReportsRoute,
  AppAdminInfluencersRoute: AppAdminInfluencersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppInfluencerIdRoute: AppInfluencerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
